---
- name: Assign name for cluster
  template: src=hostname.j2 dest=/etc/hostname

- name: Add user to sudoer file
  lineinfile: 
            dest: /etc/sudoers
            insertafter: EOF 
            line: '{{ ansible_username }} ALL=(ALL) NOPASSWD: ALL'
